source "https://rubygems.org"

gem "activerecord", "~> 6.1"
gem "sinatra-activerecord"
gem "rake"
gem "colorize"
gem "tty-prompt"

gem "require_all"
gem "sqlite3"
gem "pry"
gem 'activerecord-reset-pk-sequence'